// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.0--rc1
// source: pkg/proto/change-password/change-password.proto

package change_password

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChangePasswordServiceClient is the client API for ChangePasswordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangePasswordServiceClient interface {
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
}

type changePasswordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangePasswordServiceClient(cc grpc.ClientConnInterface) ChangePasswordServiceClient {
	return &changePasswordServiceClient{cc}
}

func (c *changePasswordServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/changepassword.ChangePasswordService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangePasswordServiceServer is the server API for ChangePasswordService service.
// All implementations must embed UnimplementedChangePasswordServiceServer
// for forward compatibility
type ChangePasswordServiceServer interface {
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	mustEmbedUnimplementedChangePasswordServiceServer()
}

// UnimplementedChangePasswordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChangePasswordServiceServer struct {
}

func (UnimplementedChangePasswordServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedChangePasswordServiceServer) mustEmbedUnimplementedChangePasswordServiceServer() {}

// UnsafeChangePasswordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangePasswordServiceServer will
// result in compilation errors.
type UnsafeChangePasswordServiceServer interface {
	mustEmbedUnimplementedChangePasswordServiceServer()
}

func RegisterChangePasswordServiceServer(s grpc.ServiceRegistrar, srv ChangePasswordServiceServer) {
	s.RegisterService(&ChangePasswordService_ServiceDesc, srv)
}

func _ChangePasswordService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangePasswordServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/changepassword.ChangePasswordService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangePasswordServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangePasswordService_ServiceDesc is the grpc.ServiceDesc for ChangePasswordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangePasswordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "changepassword.ChangePasswordService",
	HandlerType: (*ChangePasswordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangePassword",
			Handler:    _ChangePasswordService_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/change-password/change-password.proto",
}
